import React from 'react';

import './globals.css';

import { inter, noto } from './fonts';
import StyledComponentsRegistry from '@/lib/antd/AntdRegistry';
import AntdTheme from '@/lib/antd/AntdTheme';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang='en' className={`${noto.variable} ${inter.variable}`}>
    <body>
      <StyledComponentsRegistry>
        <AntdTheme>{children}</AntdTheme>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
