version: "3.8"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
  go-lang:
    container_name: go-lang
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_USER: admin
      DB_PASS: P@ssw0rd
      DB_HOST: db
      DB_NAME: loan-service
    ports:
      - 8000:8080

