import LayoutClient from "@/components/layouts";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => {
  return <LayoutClient>{children}</LayoutClient>;
};

export default RootLayout;
